### ISSUE TITLE
multipage component?

### ISSUE THREAD

**Issue by andrisi** [TaTo30/VuePDF#18]
Sorry for being a newbie pdfjs-wise, but is it a different component or way to use it, when I have one viewer, which handles paging in itself? I presume it is needed to take advantage of loading only the required pages from large docs with HTTP range requests, which are supported by pdfjs. Something like the [example from the pdfjs site](https://mozilla.github.io/pdf.js/web/viewer.html ), which also seems to use a worker process to load/render pages. Your docs seem to require a separate copy of your component for each page. Am I missing something? Otherwise excellent work, the first pdfjs component for Vue that works out of the box. Thanks a lot!

**Comment by TaTo30** [comment]
There are multipaging example in [documentation site](https://tato30.github.io/VuePDF/) 

Regarding HTTP range requests if the server supports partial content requests its should works since usePDF's src parameter is the same as pdfjs one, even if there are separate component for each page all of them use the same loading task so the document data its loaded once.

pd: sorry for replying too late, i missed this issue for some reason 😅

**Comment by andrisi** [comment]
thanks @TaTo30 will have a look and get back to you

**Comment by andrisi** [comment]
...I meant display multipage docs as Acrobat Viewer does, continously, not one page at a time. Do you have an example for that?

**Comment by TaTo30** [comment]
Iterate over the page number. Try this:

```vue
<script setup>
import { VuePDF, usePDF } from '@tato30/vue-pdf'

const { pdf, pages } = usePDF('sample.pdf')
</script>

<template>
  <div v-for="page in pages" :key="page">
    <VuePDF :pdf="pdf" :page="page" />
  </div>
</template>

```
