### ISSUE TITLE
Pinch zoom with VuePDF

### ISSUE THREAD

**Issue by janbroos** [TaTo30/VuePDF#22]
I've looked in to combine the pinch zoom on PDF.js (example on: https://gist.github.com/jsprpalm/12217feab2f1acc14bd8e8508291619e) with the VuePDF library but the quality is low since the PDF needs to scale according to the scale function on VuePDF, combining this rerenders the PDF and gives a flicker effect. 

(How) is it possible to enable pinch zoom from PDF.js in this library?

**Comment by TaTo30** [comment]
There isn't a way to enable a pinch zoom explicitly, just using the scale prop, but certainly the flickering is a issue to resolve first.

**Comment by das-friday-night** [comment]
Integration with [hammer.js](http://hammerjs.github.io/getting-started/) works for me. 
The general idea following:
1. css transform on your pdf page while you are pinching.
2. on the pinchend event of hammer.js, set the scale props of VuePDF so that the pdf render to fit new size.
3. remember to do, scrollIntoView so that your viewport is correct to focus on new position.
The basic idea is simple: set the **scale property** of your VuePDF dynamically, so that it scale as you want.
Here is a [pinch zoom example](https://codepen.io/davelinke/pen/jeMPjW) on a picture, This example inspired me a lot on how to use hammer.js.

**Comment by TaTo30** [comment]
That solution seems good!, thanks @das-friday-night
