### ISSUE TITLE
nuxt support

### ISSUE THREAD

**Issue by IgorHalfeld** [TaTo30/VuePDF#24]
any plans to have a nuxt support?

**Comment by TaTo30** [comment]
I don't know much about nuxt except it renders on server side, this library only works on client side.

Maybe there are some directives in nuxt that allows you use client side components.

**Comment by IgorHalfeld** [comment]
yep! @TaTo30, but `usePDF` composable uses client-side apis

**Comment by Suniver** [comment]
Works fine with nuxt3 for me. You just need to wrap you component with  `<ClientOnly></ClientOnly>` tags like in this example:

ParentComponent.vue
```html
<template>
  <ClientOnly>
    <ChildComponent />
  </ClientOnly>
</template>
 ```
 
 ChildComponent.vue
 ```html
 <template>
  <VuePDF :pdf="pdf" />
</template>

<script setup>
import { VuePDF, usePDF } from "@tato30/vue-pdf";
import "@tato30/vue-pdf/style.css";

const { pdf } = usePDF("file.pdf");
</script>
```

Since Nuxt3 knows you only want to use this component client side he will not call usePDF on server side. Just don't do the mistake to only wrap `<VuePDF :pdf="pdf" />` with `<ClientOnly></ClientOnly>` in your component and call usePDF in your script, nuxt will indeed try to to call udePDF server side and you will get a server 500 error.

Hope this little explanation will help future users of nuxt and VuePDF ;)

**Comment by TaTo30** [comment]
Thanks @Suniver!, very useful example.
