### ISSUE TITLE
Cannot set properties of undefined (setting 'workerSrc')

### ISSUE THREAD

**Issue by HassanJbara** [TaTo30/VuePDF#32]
Getting  `error   Cannot set properties of undefined (setting 'workerSrc')` when trying to build my static website with Astro+Vue.

**Comment by TaTo30** [comment]
Astro looks to work in ssr mode, if that is the case a solution could be wrapper this library in a client-side directive.

**Comment by albaraaf** [comment]
@TaTo30 Hi 👋 I just got the same error and I'm using NUXT 3, can you please explain a bit more about the cause of the issue and if you have any idea how to fix it with NUXT 🙏

**Comment by TaTo30** [comment]
pdf.js and therefore VuePDF are intent to work in the browser environment, if you are using a SSR framework (as Nuxt seems to be) you probably will get errors since pdf.js uses browser APIs that doesn't exists in NodeJS context.

The solution is wraps VuePDF in some of "client only" components or directives, you can find an example in this another related issue: #24

**Comment by albaraaf** [comment]
@TaTo30 Thank you that was clear and helpful 👍
