### ISSUE TITLE
Chunk size big

### ISSUE THREAD

**Issue by rxw1** [TaTo30/VuePDF#36]
Hello,

when building my thing using Vite I see a quite large chunk size for VuePDF. I've already isolated it into a separate chunk to see more clearly what's going on, but apart from that, I'm quite clueless as to why it's at almost 3 MB.

![image](https://github.com/TaTo30/VuePDF/assets/154026/7fd2d915-853d-42ec-b980-5ffdbe69d498)

Do you have any ideas? Is that normal? Even with pdf.js as a dependency, it shouldn't be that big, I guess.

Best regards

**Comment by TaTo30** [comment]
That size is because VuePDF embed pdf.worker.js in final bundle, that way isn't necessary to configure the worker in external projects.

But i've checked and noticed that there are a minified version of pdf.worker that reduce the size by 55%, isn't much but is better.

This bundle is with base pdf.worker
![imagen](https://github.com/TaTo30/VuePDF/assets/57086025/cbbd778f-ba2e-464f-b23e-b2cee75393b4)

...and this bundle is with minified pdf.worker
![imagen](https://github.com/TaTo30/VuePDF/assets/57086025/42cf031e-1b26-4bd4-b44d-6ae3914af613)
