### ISSUE TITLE
Setting the quality (compression) of the display

### ISSUE THREAD

**Issue by alepsrp** [TaTo30/VuePDF#41]
Have a good day!
When displaying images, sometimes they are not quite readable. poor quality . how can i render for better quality, maybe there are options or methods?
Thanks for the help!

**Comment by etischenko** [comment]
+1

I'm migrating the project from Vue2 to Vue3 and wanted to replace the vue-pdf library with this one, but the display quality feels much worse, especially with images that include thin lines :(. Are there any plans to improve it?

Love that it's implemented with Composition API.

**Comment by dev-mantas** [comment]
+1 
Yeah small text is really blurry on mobile phones, works great on desktops though.

**Comment by TaTo30** [comment]
Surely is a issue related to `devicePixelRatio` as @batchfy-bot mentioned, thanks a lot for the reference.

If there are still issues with the quality, feel free to reopen this thread.

**Comment by rxw1** [comment]
Hi!

Something might be wrong about the deployment of version 1.7.2.

If I install the package via `npm i @tato30/vue-pdf` the devicePixelRatio fix doesn't seem to kick in, i.e. PDFs are displayed very blurry when zoomed or on some mobiles.

I've checked and the package from npm does seem to contain the fix.

On the other hand, when I copy the src directory directly to the sources of my project, the fix is applied and PDFs are displayed crisp and nice.

I've made a small working example here: https://github.com/rxw1/VuePDF-min

You can take a look at these two lines https://github.com/rxw1/VuePDF-min/blob/master/src/App.vue#L3-L4 and switch back and forth between installations.

I'm not so sure about what's going on.

https://github.com/TaTo30/VuePDF/assets/154026/654550f1-1b0f-46f0-9aa6-c1396bb816bd

**Comment by TaTo30** [comment]
You're right @rxw1, there was a problem with the bundle deploy, it's already fixed.

**Comment by rxw1** [comment]
Thank you!
