### ISSUE TITLE
Ensuring Reactivity

### ISSUE THREAD

**Issue by MM-coder** [TaTo30/VuePDF#54]
How can I pass a ref to the `usePDF´ to properly ensure reactivity so that if the ref's value changes the PDF will change.

My current implementation is linked below:
https://github.com/librecharts/webpage/blob/master/src/components/PDFViewer.vue

This has a few shortcomings:
- It re-assigns refs which shouldn't be done
- Rotation does not work
- Desctruction does not work (the canvas remains)

Are refs and reactivity a planned thing for this library?

Kind regards
Mauro M.

**Comment by TaTo30** [comment]
Hi,

`usePDF` is an additional feature in order to do "easy" implementations and its use isn't required at all as explained here: https://tato30.github.io/VuePDF/guide/composables.html#custom, it wasn't planned as reactivity thing but you have a point that is very awful re-assigns refs objects, i will think on some workarounds.

Meanwhile you can try to follow this example: https://tato30.github.io/VuePDF/examples/advanced/multiple_pdf.html
